# Generated by Django 4.2.2 on 2023-06-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meet_app", "0006_alter_participant_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="email",
        ),
    ]
