# Generated by Django 4.2.2 on 2023-06-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meet_app", "0007_remove_participant_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
