# Generated by Django 4.2.2 on 2023-06-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meet_app", "0008_alter_participant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
