# Generated by Django 4.2.2 on 2023-06-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meet_app", "0011_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="latitude",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participant",
            name="longitude",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
